### ISSUE TITLE
[YAML.ahk]  Indentation problem.

### ISSUE THREAD

**Issue by lstrfwp** [thqby/ahk2_lib#74]
This can be parsed:
```
text := "
(
Item:
  - a: hello
    b: world
    c:
      - subitem1
      - subitem2
)"

obj := YAML.parse(text)
```
But If I move `b` after `c`, it throws an indentation error:
```
text := "
(
Item:
  - a: hello
    c:
      - subitem1
      - subitem2
    b: world
)"

obj := YAML.parse(text)
```

**Comment by thqby** [comment]
This is a long-standing issue.
This can also be parsed.
```yaml
Item:
  - 
    a: hello
    c:
      - subitem1
      - subitem2
    b: world
```
